//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.30 at 12:57:23 PM MSK 
//


package cselp.domain.opensky;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LEGType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LEGType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TAIL_NO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ORIGIN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DESTINATION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DEPARTURE_PLAN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ARRIVAL_PLAN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DEPARTURE_FACT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ARRIVAL_FACT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TAKE_OFF" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TOUCH_DOWN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CREW_TASK" type="{}CREW_TASKType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LEGType", propOrder = {
    "tailno",
    "origin",
    "destination",
    "departureplan",
    "arrivalplan",
    "departurefact",
    "arrivalfact",
    "takeoff",
    "touchdown",
    "crewtask"
})
public class LEGType {

    @XmlElement(name = "TAIL_NO", required = true)
    protected String tailno;
    @XmlElement(name = "ORIGIN", required = true)
    protected String origin;
    @XmlElement(name = "DESTINATION", required = true)
    protected String destination;
    @XmlElement(name = "DEPARTURE_PLAN", required = true)
    protected String departureplan;
    @XmlElement(name = "ARRIVAL_PLAN", required = true)
    protected String arrivalplan;
    @XmlElement(name = "DEPARTURE_FACT", required = true)
    protected String departurefact;
    @XmlElement(name = "ARRIVAL_FACT", required = true)
    protected String arrivalfact;
    @XmlElement(name = "TAKE_OFF", required = true)
    protected String takeoff;
    @XmlElement(name = "TOUCH_DOWN", required = true)
    protected String touchdown;
    @XmlElement(name = "CREW_TASK")
    protected List<CREWTASKType> crewtask;

    /**
     * Gets the value of the tailno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAILNO() {
        return tailno;
    }

    /**
     * Sets the value of the tailno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAILNO(String value) {
        this.tailno = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORIGIN() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORIGIN(String value) {
        this.origin = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESTINATION() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESTINATION(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the departureplan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEPARTUREPLAN() {
        return departureplan;
    }

    /**
     * Sets the value of the departureplan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEPARTUREPLAN(String value) {
        this.departureplan = value;
    }

    /**
     * Gets the value of the arrivalplan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getARRIVALPLAN() {
        return arrivalplan;
    }

    /**
     * Sets the value of the arrivalplan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setARRIVALPLAN(String value) {
        this.arrivalplan = value;
    }

    /**
     * Gets the value of the departurefact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEPARTUREFACT() {
        return departurefact;
    }

    /**
     * Sets the value of the departurefact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEPARTUREFACT(String value) {
        this.departurefact = value;
    }

    /**
     * Gets the value of the arrivalfact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getARRIVALFACT() {
        return arrivalfact;
    }

    /**
     * Sets the value of the arrivalfact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setARRIVALFACT(String value) {
        this.arrivalfact = value;
    }

    /**
     * Gets the value of the takeoff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAKEOFF() {
        return takeoff;
    }

    /**
     * Sets the value of the takeoff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAKEOFF(String value) {
        this.takeoff = value;
    }

    /**
     * Gets the value of the touchdown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOUCHDOWN() {
        return touchdown;
    }

    /**
     * Sets the value of the touchdown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOUCHDOWN(String value) {
        this.touchdown = value;
    }

    /**
     * Gets the value of the crewtask property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the crewtask property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCREWTASK().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CREWTASKType }
     * 
     * 
     */
    public List<CREWTASKType> getCREWTASK() {
        if (crewtask == null) {
            crewtask = new ArrayList<CREWTASKType>();
        }
        return this.crewtask;
    }

}
