//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.30 at 12:57:23 PM MSK 
//


package cselp.domain.opensky;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MEMBERSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MEMBERSType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MEMBER" type="{}MEMBERType"/>
 *         &lt;element name="LEG_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ROLE" type="{}ROLEType"/>
 *         &lt;element name="DUTY_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MEMBERSType", propOrder = {
    "member",
    "legtype",
    "role",
    "dutytype"
})
public class MEMBERSType {

    @XmlElement(name = "MEMBER", required = true)
    protected MEMBERType member;
    @XmlElement(name = "LEG_TYPE", required = true)
    protected String legtype;
    @XmlElement(name = "ROLE", required = true)
    protected ROLEType role;
    @XmlElement(name = "DUTY_TYPE", required = true)
    protected String dutytype;

    /**
     * Gets the value of the member property.
     * 
     * @return
     *     possible object is
     *     {@link MEMBERType }
     *     
     */
    public MEMBERType getMEMBER() {
        return member;
    }

    /**
     * Sets the value of the member property.
     * 
     * @param value
     *     allowed object is
     *     {@link MEMBERType }
     *     
     */
    public void setMEMBER(MEMBERType value) {
        this.member = value;
    }

    /**
     * Gets the value of the legtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEGTYPE() {
        return legtype;
    }

    /**
     * Sets the value of the legtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEGTYPE(String value) {
        this.legtype = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link ROLEType }
     *     
     */
    public ROLEType getROLE() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link ROLEType }
     *     
     */
    public void setROLE(ROLEType value) {
        this.role = value;
    }

    /**
     * Gets the value of the dutytype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDUTYTYPE() {
        return dutytype;
    }

    /**
     * Sets the value of the dutytype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDUTYTYPE(String value) {
        this.dutytype = value;
    }

}
