//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.30 at 12:57:23 PM MSK 
//


package cselp.domain.opensky;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cselp.domain.opensky package.
 * <p>An ObjectFactory allows you to programmatically
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PERFORMEDFLIGHTS_QNAME = new QName("", "PERFORMED_FLIGHTS");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cselp.domain.opensky
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PERFORMEDFLIGHTSType }
     * 
     */
    public PERFORMEDFLIGHTSType createPERFORMEDFLIGHTSType() {
        return new PERFORMEDFLIGHTSType();
    }

    /**
     * Create an instance of {@link CREWTASKType }
     * 
     */
    public CREWTASKType createCREWTASKType() {
        return new CREWTASKType();
    }

    /**
     * Create an instance of {@link MINIMUMSType }
     * 
     */
    public MINIMUMSType createMINIMUMSType() {
        return new MINIMUMSType();
    }

    /**
     * Create an instance of {@link ROLEType }
     * 
     */
    public ROLEType createROLEType() {
        return new ROLEType();
    }

    /**
     * Create an instance of {@link LEGType }
     * 
     */
    public LEGType createLEGType() {
        return new LEGType();
    }

    /**
     * Create an instance of {@link MEMBERType }
     * 
     */
    public MEMBERType createMEMBERType() {
        return new MEMBERType();
    }

    /**
     * Create an instance of {@link MEMBERSType }
     * 
     */
    public MEMBERSType createMEMBERSType() {
        return new MEMBERSType();
    }

    /**
     * Create an instance of {@link FLIGHTType }
     * 
     */
    public FLIGHTType createFLIGHTType() {
        return new FLIGHTType();
    }

    /**
     * Create an instance of {@link DIVISIONType }
     * 
     */
    public DIVISIONType createDIVISIONType() {
        return new DIVISIONType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PERFORMEDFLIGHTSType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PERFORMED_FLIGHTS")
    public JAXBElement<PERFORMEDFLIGHTSType> createPERFORMEDFLIGHTS(PERFORMEDFLIGHTSType value) {
        return new JAXBElement<PERFORMEDFLIGHTSType>(_PERFORMEDFLIGHTS_QNAME, PERFORMEDFLIGHTSType.class, null, value);
    }

}
