//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.30 at 03:41:04 PM MSK 
//


package cselp.domain.opensky;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ROLEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ROLEType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FLIGHT_ROLE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DIVISION_ROLE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DIVISION_ROLE_ID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ROLEType", propOrder = {
    "flightrole",
    "divisionrole",
    "divisionroleid"
})
public class ROLEType {

    @XmlElement(name = "FLIGHT_ROLE", required = true)
    protected String flightrole;
    @XmlElement(name = "DIVISION_ROLE", required = true)
    protected String divisionrole;
    @XmlElement(name = "DIVISION_ROLE_ID")
    protected long divisionroleid;

    /**
     * Gets the value of the flightrole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFLIGHTROLE() {
        return flightrole;
    }

    /**
     * Sets the value of the flightrole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFLIGHTROLE(String value) {
        this.flightrole = value;
    }

    /**
     * Gets the value of the divisionrole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDIVISIONROLE() {
        return divisionrole;
    }

    /**
     * Sets the value of the divisionrole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDIVISIONROLE(String value) {
        this.divisionrole = value;
    }

    /**
     * Gets the value of the divisionroleid property.
     * 
     */
    public long getDIVISIONROLEID() {
        return divisionroleid;
    }

    /**
     * Sets the value of the divisionroleid property.
     * 
     */
    public void setDIVISIONROLEID(long value) {
        this.divisionroleid = value;
    }

}
